apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
    app: deploy
spec:
  selector:
    matchLabels:
      app: pod-nginx
  template:
    metadata:
      labels:
        app: pod-nginx
    spec:
      volumes: 
      - name: v1
        persistentVolumeClaim: 
          claimName: vol-clain 
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: v1
          mountPath: /var/shared-data/
  replicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  selector:
    app: pod-nginx
  ports:
  - port: 80
    targetPort: 80

