apiVersion: v1
kind: Pod
metadata:
  name: pod-emptydir
spec:
  nodeName: node1
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
    - mountPath: /backup
      name: backup-volume
  volumes:
  - name: backup-volume
    emptyDir: {}
