apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 8.8.8.8
    - 10.96.0.10
    searches: ['cluster.local']
