apiVersion: v1
kind: Namespace
metadata:
  name: limitspace
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-resources
  namespace: limitspace
spec:
  limits:
  - type: Pod
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 200m
      memory: 6Mi
  - type: Container
    default:
      cpu: 300m
      memory: 200Mi
    defaultRequest:
      cpu: 200m
      memory: 100Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 3Mi
