apiVersion: v1
kind: Pod
metadata:
  name: pod-web
spec:
  containers:
  - name: apache
    image: httpd:alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-web2
spec:
  containers:
  - name: apache2
    image: httpd:alpine
    ports:
    - containerPort: 80
